#!/bin/sh

# Copyright (C) 2024 Geophysical Fluid Dynamics Laboratory

# This file is part of the GFDL FRE NetCDF tools package (FRE-NCTools).

# FRE-NCtools is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# FRE-NCtools is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.

# You should have received a copy of the GNU Lesser General Public
# License along with FRE-NCTools.  If not, see
# <http://www.gnu.org/licenses/>.

# This test verifies iceberg_comb.sh will report if a file is a valid
# iceberg file.

if test "$VERBOSE" = yes
then
    set -x
    command -v iceberg_comb.sh
    iceberg_comb.sh -V
fi

. "$srcdir/init.sh"

# Create the un-combined files
ncgen -o iceberg.nc.0000 << EOF || framework_failure_
netcdf iceberg_test.nc {
dimensions:
  i = UNLIMITED ; // (5 currently)
variables:
  double lon(i) ;
    lon:long_name = "longitude" ;
    lon:units = "degrees_E" ;
  double lat(i) ;
    lat:long_name = "latitude" ;
    lat:units = "degrees_N" ;
    int i ;
// global attributes:
                :NumFilesInSet = 3 ;
                :file_format_major_version = 0 ;
                :file_format_minor_version = 1 ;
                :time_axis = 0 ;
data:
  i = 5 ;
  lon = 1, 2, 3, 4, 5 ;
  lat = 15, 14, 13, 12, 11 ;
}
EOF

ncgen -o not-iceberg-badversion.nc.0000 << EOF || framework_failure_
netcdf iceberg_test.nc {
dimensions:
  i = UNLIMITED ; // (2 currently)
variables:
  double lon(i) ;
    lon:long_name = "longitude" ;
    lon:units = "degrees_E" ;
  double lat(i) ;
    lat:long_name = "latitude" ;
    lat:units = "degrees_N" ;
    int i ;
// global attributes:
                :NumFilesInSet = 3 ;
                :file_format_major_version = 0 ;
                :file_format_minor_version = 0 ;
                :time_axis = 0 ;
data:
  i = 5 ;
  lon = 6, 7 ;
  lat = 10, 9 ;
}
EOF

ncgen -o not-iceberg-nosetnumber.nc.0000 << EOF || framework_failure_
netcdf iceberg_test.nc {
dimensions:
  i = UNLIMITED ; // (8 currently)
variables:
  double lon(i) ;
    lon:long_name = "longitude" ;
    lon:units = "degrees_E" ;
  double lat(i) ;
    lat:long_name = "latitude" ;
    lat:units = "degrees_N" ;
    int i ;
// global attributes:
                :file_format_major_version = 0 ;
                :file_format_minor_version = 1 ;
                :time_axis = 0 ;
data:
  i = 5 ;
  lon = 8, 9, 10, 11, 12, 13, 14, 15 ;
  lat = 8, 7, 6, 5, 4, 3, 2, 1 ;
}
EOF

ncgen -o not-iceberg-noversion.nc.0000 << EOF || framework_failure_
netcdf iceberg_test.nc {
dimensions:
  i = UNLIMITED ; // (5 currently)
variables:
  double lon(i) ;
    lon:long_name = "longitude" ;
    lon:units = "degrees_E" ;
  double lat(i) ;
    lat:long_name = "latitude" ;
    lat:units = "degrees_N" ;
    int i ;
// global attributes:
                :NumFilesInSet = 3 ;
                :time_axis = 0 ;
data:
  i = 5 ;
  lon = 1, 2, 3, 4, 5 ;
  lat = 15, 14, 13, 12, 11 ;
}
EOF

iceberg_comb.sh -c iceberg.nc.0000 || fail_ checking valid iceberg file
iceberg_comb.sh -c not-iceberg-badversion.nc.0000
test $? -eq 255 || fail_ check iceberg file with bad version, incorrect return status
iceberg_comb.sh -c not-iceberg-nosetnumber.nc.0000
test $? -eq 255 || fail_ check iceberg file no NumFilesInSet, incorrect return status
iceberg_comb.sh -c not-iceberg-noversion.nc.0000
test $? -eq 255 || fail_ check iceberg file with no version, incorrect return status

Exit $fail