#!/bin/sh

# Copyright (C) 2024 Geophysical Fluid Dynamics Laboratory

# This file is part of the GFDL FRE NetCDF tools package (FRE-NCTools).

# FRE-NCtools is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# FRE-NCtools is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.

# You should have received a copy of the GNU Lesser General Public
# License along with FRE-NCTools.  If not, see
# <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes
then
    set -x
fi

#. "${srcdir=.}/init.sh"

# create C48 grid for atmos/land
make_hgrid \
    --grid_type gnomonic_ed \
    --nlon 96 \
    --grid_name C48_grid || framework_failure_ failed to create C48 grid

# create C48 solo mosaic for atmos/land
make_solo_mosaic \
    --num_tiles 6 \
    --dir . \
    --mosaic C48_mosaic \
    --tile_file C48_grid.tile1.nc,C48_grid.tile2.nc,C48_grid.tile3.nc,C48_grid.tile4.nc,C48_grid.tile5.nc,C48_grid.tile6.nc \
    || framework_failure_ failed to create C48 solo mosaic

${builddir=..}/create_regional_file -t 3 -g 48 \
    || framework_failure_ Failed to create the regional file rregional_input_file.tile3.nc

make_regional_mosaic \
    --global_mosaic C48_mosaic.nc \
    --regional_file rregion_input_file.tile3.nc \
    || fail_ Make_regional_mosaic failed for tile 3
test -f regional_mosaic.nc \
    || fail_ regional_mosaic.nc file not found
test -f regional_grid.tile3.nc \
    || fail_ regional_grid.tile3.nc file not found

# Create a tile 4 regional file, and mosaic
${builddir}/create_regional_file -t 4 -g 48 \
    || framework_failure_ failed to create regional file rregional_input_file.tile4.nc
make_regional_mosaic \
    --global_mosaic C48_mosaic.nc \
    --regional_file rregion_input_file.tile4.nc \
    || fail_ Make_regional_mosaic failed for tile 4
test -f regional_mosaic.nc \
    || fail_ regional_mosaic.nc file not found
test -f regional_grid.tile4.nc \
    || fail_ regional_grid.tile4.nc file not found
