package:
  name: fre-nctools
  version: alpha

source:
  path: .

build:
  number: 0

requirements:
  build:
    - conda-forge::nco
    - conda-forge::libnetcdf
    - conda-forge::netcdf-fortran
    - conda-forge::mpich
    - conda-forge::gfortran
    - conda-forge::python>2
    - conda-forge::numpy
    - conda-forge::pytest
    - conda-forge::libtool
    - conda-forge::autoconf
    - conda-forge::automake
    - conda-forge::hdf5=1.14.*=mpi*
    - conda-forge::openmp
    - conda-forge::tcsh
  run:

test:
  commands:
    - echo 'yay! we made it!'
    - pwd && ls
#    - autoreconf -i
#    - ./configure
    - which timavg.csh
    - timavg.csh --help
#    - make check

about:
  license: LGPL-3.0
  summary: Tools for manipulating and creating netCDF inputs for FMS managed models
