package:
  name: fre-nctools
  version: alpha

source:
  path: .

build:
  number: 0

requirements:
  build:
    - conda-forge::nco
    - conda-forge::libnetcdf
    - conda-forge::netcdf-fortran
    - conda-forge::mpich
    - conda-forge::gfortran
    - conda-forge::python>2
    - conda-forge::numpy
    - conda-forge::pytest
    - conda-forge::libtool
    - conda-forge::autoconf
    - conda-forge::automake
    - conda-forge::hdf5=1.14.*=mpi*
    - conda-forge::openmp
    - conda-forge::tcsh
    - conda-forge::which
  run:

test:
  source_files:
    - tests/**
    - src/**
    - m4/**
    - configure.ac
    - Makefile.am
  commands:
    - echo 'Testing FRE-NCtools conda package installation...'
    - echo "Installation directory:" && pwd
    - echo "Contents of Installation directory:" && ls
    
    # Test key installed programs with help flags (allow help commands to exit with any status)
    - echo "Testing timavg script..." && which timavg && (timavg -h || echo "timavg help command completed")
    - echo "Testing ncexists program..." && which ncexists && (ncexists --help || echo "ncexists help command completed")
    - echo "Testing combine-ncc program..." && which combine-ncc && (combine-ncc --help || echo "combine-ncc help command completed")
    - echo "Testing fregrid program..." && which fregrid && (fregrid --help || echo "fregrid help command completed")
    - echo "Testing make_hgrid program..." && which make_hgrid && (make_hgrid --help || echo "make_hgrid help command completed")
    - echo "Testing check_mask program..." && which check_mask && (check_mask 2>&1 | grep -q "check_mask --grid_file" && echo "check_mask usage displayed correctly" || echo "check_mask found")
    
    # Test some key script utilities exist
    - echo "Testing list_ncvars.sh script..." && which list_ncvars.sh && echo "list_ncvars.sh found"
    - echo "Testing split_ncvars.pl script..." && which split_ncvars.pl && echo "split_ncvars.pl found"
    
    # Test version reporting for programs that support it (allow version commands to exit with any status)
    - echo "Testing version reporting..." && (ncexists --version || echo "ncexists version command completed")
    - echo "Testing combine-ncc version..." && (combine-ncc --version || echo "combine-ncc version command completed")  
    - echo "Testing timavg version..." && (timavg -V || echo "timavg version command completed")
    
    # Run actual tests using the repository's test infrastructure
    - echo "Setting up test environment..." && autoreconf -i . && ./configure && make check RUN_EXPENSIVE_TESTS=no
    
    - echo 'All tests completed - FRE-NCtools installation verified!'

about:
  license: LGPL-3.0
  summary: Tools for manipulating and creating netCDF inputs for FMS managed models
