package:
  name: fre-nctools
  version: conda.alpha

source:
  path: .

build:
  number: 0

requirements:
  build:
    - conda-forge::libnetcdf
    - conda-forge::netcdf-fortran
    - conda-forge::nco
    - conda-forge::hdf5=1.14.*=mpi*
    - conda-forge::openmp
    - conda-forge::tcsh
  run:

test:
  commands:
    - make check-expensive

about:
  license: LGPL-3.0
  summary: Tools for manipulating and creating netCDF inputs for FMS managed models
