package:
  name: fre-nctools
  version: '{{ environ.get("GIT_DESCRIBE_TAG", data.get("version")) }}'

source:
  path: .

build:
  number: 0

requirements:
  build:
    - libnetcdf
    - netcdf-fortran
  run:

test:
  commands:
    - make check-expensive

about:
  license: LGPL-3.0
  summary: Tools for manipulating and creating netCDF inputs for FMS managed models
