package:
  name: fre-nctools
  version: alpha

source:
  path: .

build:
  number: 0

requirements:
  build:
    - conda-forge::nco
    - conda-forge::libnetcdf
    - conda-forge::netcdf-fortran
    - conda-forge::mpich
    - conda-forge::gfortran
    - conda-forge::python>2
    - conda-forge::numpy
    - conda-forge::pytest
    - conda-forge::libtool
    - conda-forge::autoconf
    - conda-forge::automake
    - conda-forge::hdf5=1.14.*=mpi*
    - conda-forge::openmp
    - conda-forge::tcsh
    - conda-forge::which
  run:

test:
  commands:
    - echo 'yay! we made it!'
    - echo "whereami? what is here...?" && pwd && ls
#    - autoreconf -i
#    - ./configure
    - echo "which timavg is it...?  " && which timavg
    - echo "timavg --help is...?" && timavg --help
    - echo "make check RUN_EXPENSIVE_TESTS=no...?" && make check RUN_EXPENSIVE_TESTS=no
#    - make check

about:
  license: LGPL-3.0
  summary: Tools for manipulating and creating netCDF inputs for FMS managed models
