#!/bin/sh

# Copyright (C) 2024 Geophysical Fluid Dynamics Laboratory

# This file is part of the GFDL FRE NetCDF tools package (FRE-NCTools).

# FRE-NCtools is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# FRE-NCtools is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.

# You should have received a copy of the GNU Lesser General Public
# License along with FRE-NCTools.  If not, see
# <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes
then
    set -x
fi

. "${srcdir=.}/init.sh"


make_hgrid \
    --grid_type gnomonic_ed \
    --nlon 96 \
    --grid_name C48_grid \
    || framework_failure_ failed to create C48 grid files

# Create the required input files
${builddir=..}/create_daily_tile_files C48_grid || framework_failure_ failed to create daily tile files

make_solo_mosaic \
    --num_tiles 6 \
    --dir ./ \
    --mosaic_name C48_mosaic \
    --tile_file C48_grid.tile1.nc,C48_grid.tile2.nc,C48_grid.tile3.nc,C48_grid.tile4.nc,C48_grid.tile5.nc,C48_grid.tile6.nc \
    || framework_failure_ failed to create C48 mosaic files

mkdir -p output || framework_failure_ failed to create output directory
fregrid \
	--input_mosaic C48_mosaic.nc \
	--input_file test_output \
	--scalar_field static,tvar \
	--nlon 144 \
	--nlat 90 \
	--interp_method conserve_order2 \
	--output_dir output \
	--output_file fregrid_output.nc \
	--check_conserve \
	--remap_file C48_to_N45_remap.nc \
    || fail_ failed running fregrid
test -f output/fregrid_output.nc || fail_ output/fregrid_output.nc not found
test -f C48_to_N45_remap.nc || fail_ C48_to_N45_remap.nc not found