#!/bin/sh

# ensure the help option prints something and exits successfully

# Copyright (C) 2024 Geophysical Fluid Dynamics Laboratory

# This file is part of the GFDL FRE NetCDF tools package (FRE-NCTools).

# FRE-NCtools is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# FRE-NCtools is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.

# You should have received a copy of the GNU Lesser General Public
# License along with FRE-NCTools.  If not, see
# <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes
then
    set -x
    command -v mppnccombine
    mppnccombine -V
fi

. "$srcdir/init.sh"

# Create the four decomposed NetCDF files
ncgen -o decomp.nc.0000 << EOF || framework_failure
netcdf compress {
dimensions:
  grid_xt = 10 ;
  grid_yt = 2 ;
  time = UNLIMITED ; // (1 currently)
variables:
  double grid_xt(grid_xt) ;
    grid_xt:long_name = "T-cell longitude" ;
    grid_xt:units = "degrees_E" ;
    grid_xt:axis = "X" ;
    grid_xt:domain_decomposition = 1, 10, 1, 10 ;
  double grid_yt(grid_yt) ;
    grid_yt:long_name = "T-cell latitude" ;
    grid_yt:units = "degrees_N" ;
    grid_yt:axis = "Y" ;
    grid_yt:domain_decomposition = 1, 8, 1, 2 ;
  double time(time) ;
    time:long_name = "time" ;
    time:units = "days since 0001-01-01 00:00:00" ;
    time:axis = "T" ;
    time:calendar_type = "NOLEAP" ;
    time:calendar = "noleap" ;
  float var(grid_yt, grid_xt) ;
    var:long_name = "Decomposed variable" ;
    var:units = "m" ;
    var:missing_value = 1.e+20f ;
    var:_FillValue = 1.e+20f ;
    var:dummy_attribute = "just a dummy attribute" ;
// global attributed:
  :filename = "decomp.nc.0000" ;
  :NumFilesInSet = 4 ;
  :dummy_global_att = "a global dummy attribute" ;
data:
  grid_xt = 0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0 ;
  grid_yt = 0.0, 1.0  ;
  time = 0 ;
  var =
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9,
    10, 11, 12, 13, 14, 15, 16, 17, 18, 19 ;
}
EOF

ncgen -o decomp.nc.0001 << EOF || framework_failure
netcdf compress {
dimensions:
  grid_xt = 10 ;
  grid_yt = 2 ;
  time = UNLIMITED ; // (1 currently)
variables:
  double grid_xt(grid_xt) ;
    grid_xt:long_name = "T-cell longitude" ;
    grid_xt:units = "degrees_E" ;
    grid_xt:axis = "X" ;
    grid_xt:domain_decomposition = 1, 10, 1, 10 ;
  double grid_yt(grid_yt) ;
    grid_yt:long_name = "T-cell latitude" ;
    grid_yt:units = "degrees_N" ;
    grid_yt:axis = "Y" ;
    grid_yt:domain_decomposition = 1, 8, 3, 4 ;
  double time(time) ;
    time:long_name = "time" ;
    time:units = "days since 0001-01-01 00:00:00" ;
    time:axis = "T" ;
    time:calendar_type = "NOLEAP" ;
    time:calendar = "noleap" ;
  float var(grid_yt, grid_xt) ;
    var:long_name = "Decomposed variable" ;
    var:units = "m" ;
    var:missing_value = 1.e+20f ;
    var:_FillValue = 1.e+20f ;
    var:dummy_attribute = "just a dummy attribute" ;
// global attributed:
  :filename = "decomp.nc.0001" ;
  :NumFilesInSet = 4 ;
  :dummy_global_att = "a global dummy attribute" ;
data:
  grid_xt = 0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0 ;
  grid_yt = 2.0, 3.0 ;
  time = 0 ;
  var =
    20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
    30, 31, 32, 33, 34, 35, 36, 37, 38, 39 ;
}
EOF

ncgen -o decomp.nc.0002 << EOF || framework_failure
netcdf compress {
dimensions:
  grid_xt = 10 ;
  grid_yt = 2 ;
  time = UNLIMITED ; // (1 currently)
variables:
  double grid_xt(grid_xt) ;
    grid_xt:long_name = "T-cell longitude" ;
    grid_xt:units = "degrees_E" ;
    grid_xt:axis = "X" ;
    grid_xt:domain_decomposition = 1, 10, 1, 10 ;
  double grid_yt(grid_yt) ;
    grid_yt:long_name = "T-cell latitude" ;
    grid_yt:units = "degrees_N" ;
    grid_yt:axis = "Y" ;
    grid_yt:domain_decomposition = 1, 8, 5, 6 ;
  double time(time) ;
    time:long_name = "time" ;
    time:units = "days since 0001-01-01 00:00:00" ;
    time:axis = "T" ;
    time:calendar_type = "NOLEAP" ;
    time:calendar = "noleap" ;
  float var(grid_yt, grid_xt) ;
    var:long_name = "Decomposed variable" ;
    var:units = "m" ;
    var:missing_value = 1.e+20f ;
    var:_FillValue = 1.e+20f ;
    var:dummy_attribute = "just a dummy attribute" ;
// global attributed:
  :filename = "decomp.nc.0002" ;
  :NumFilesInSet = 4 ;
  :dummy_global_att = "a global dummy attribute" ;
data:
  grid_xt = 0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0 ;
  grid_yt = 4.0, 5.0 ;
  time = 0 ;
  var =
    40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
    50, 51, 52, 53, 54, 55, 56, 57, 58, 59 ;
}
EOF

ncgen -o decomp.nc.0003 << EOF || framework_failure
netcdf compress {
dimensions:
  grid_xt = 10 ;
  grid_yt = 2 ;
  time = UNLIMITED ; // (1 currently)
variables:
  double grid_xt(grid_xt) ;
    grid_xt:long_name = "T-cell longitude" ;
    grid_xt:units = "degrees_E" ;
    grid_xt:axis = "X" ;
    grid_xt:domain_decomposition = 1, 10, 1, 10 ;
  double grid_yt(grid_yt) ;
    grid_yt:long_name = "T-cell latitude" ;
    grid_yt:units = "degrees_N" ;
    grid_yt:axis = "Y" ;
    grid_yt:domain_decomposition = 1, 8, 7, 8 ;
  double time(time) ;
    time:long_name = "time" ;
    time:units = "days since 0001-01-01 00:00:00" ;
    time:axis = "T" ;
    time:calendar_type = "NOLEAP" ;
    time:calendar = "noleap" ;
  float var(grid_yt, grid_xt) ;
    var:long_name = "Decomposed variable" ;
    var:units = "m" ;
    var:missing_value = 1.e+20f ;
    var:_FillValue = 1.e+20f ;
    var:dummy_attribute = "just a dummy attribute" ;
// global attributed:
  :filename = "decomp.nc.0003" ;
  :NumFilesInSet = 4 ;
  :dummy_global_att = "a global dummy attribute" ;
data:
  grid_xt = 0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0 ;
  grid_yt = 6.0, 7.0 ;
  time = 0 ;
  var =
    60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
    70, 71, 72, 73, 74, 75, 76, 77, 78, 79 ;
}
EOF

# run mppnccombine to generate decomp.nc, not
# listing other input files
mppnccombine decomp.nc || fail=1
# verify that mppnccombine generated a good netcdf file
output=$(ncdump decomp.nc) || fail=1
# verify that the var variable has the correct number of elements
# and are in the correct order
echo $output | grep -q "var *= *$(seq -s ', *' 0 78) *79 *;" || fail=1
# verify the global variable NumFilesInSet is gone
echo $output | grep -q ":NumFilesInSet *= *\d *" && fail=1
# verify that the domain_decomposition for grid_[xy]t is gond
echo $output | grep -q "grid_[xy]t:domain_decomposition *=" && fail=1
# verify the dummy attributes (global and variable) are in the final file
echo $output | grep -q ":dummy_global_att *=" || fail=1
echo $output | grep -q "var:dummy_attribute *=" || fail=1

Exit $fail
