#!/bin/sh

# Copyright (C) 2024 Geophysical Fluid Dynamics Laboratory

# This file is part of the GFDL FRE NetCDF tools package (FRE-NCTools).

# FRE-NCtools is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# FRE-NCtools is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.

# You should have received a copy of the GNU Lesser General Public
# License along with FRE-NCTools.  If not, see
# <http://www.gnu.org/licenses/>.

# This script will create the required files to test the hydrology tools

# Create ocean hgrid
make_hgrid \
    --grid_type tripolar_grid \
    --nxbnd 2 \
    --nybnd 7 \
    --xbnd -280,80 \
    --ybnd -82,-30,-10,0,10,30,90 \
    --dlon 1.0,1.0 \
    --dlat 1.0,1.0,0.6666667,0.3333333,0.6666667,1.0,1.0 \
    --grid_name ocean_hgrid \
    --center c_cell

# create ocean_vgrid
make_vgrid \
    --nbnds 3 \
    --bnds 0.,220.,5500. \
    --dbnds 10.,10.,367.14286 \
    --center c_cell \
    --grid_name ocean_vgrid

# create ocean solo mosaic
make_solo_mosaic \
    --num_tiles 1 \
    --dir . \
    --mosaic_name ocean_mosaic \
    --tile_file ocean_hgrid.nc \
    --periodx 360

# create ocean topography data
"${builddir=..}"/create_5degree_topog
make_topog \
    --mosaic ocean_mosaic.nc \
    --topog_type realistic \
    --topog_file 5degree_topog.nc \
    --topog_field TOPO \
    --scale_factor -1 \
    --vgrid ocean_vgrid.nc \
    --output topog.nc

# create C48 grid for atmos/land
make_hgrid \
    --grid_type gnomonic_ed \
    --nlon 96 \
    --grid_name C48_grid

# create C48 solo mosaic for atmos/land
make_solo_mosaic \
    --num_tiles 6 \
    --dir . \
    --mosaic C48_mosaic \
    --tile_file C48_grid.tile1.nc,C48_grid.tile2.nc,C48_grid.tile3.nc,C48_grid.tile4.nc,C48_grid.tile5.nc,C48_grid.tile6.nc

# create coupler_mosaic
make_coupler_mosaic \
    --atmos_mosaic C48_mosaic.nc \
    --ocean_mosaic ocean_mosaic.nc \
    --ocean_topog  topog.nc \
    --check \
    --area_ratio_thresh 1.e-10 \
    --mosaic_name grid_spec

# Create river regrid input
"${builddir=..}/create_river_regrid_file"

# Create a river regrid
river_regrid \
    --mosaic grid_spec.nc \
    --river_src river_regrid_input.nc \
    --output river_data_C48 \
    --land_thresh 0.000001
