#!/bin/sh

# Copyright (C) 2024 Geophysical Fluid Dynamics Laboratory

# This file is part of the GFDL FRE NetCDF tools package (FRE-NCTools).

# FRE-NCtools is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# FRE-NCtools is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.

# You should have received a copy of the GNU Lesser General Public
# License along with FRE-NCTools.  If not, see
# <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes
then
    set -x
fi

. "${srcdir=.}/init.sh"

# create ocean_vgrid
make_vgrid \
    --nbnds 3 \
    --bnds 0.,220.,5500. \
    --dbnds 10.,10.,367.14286 \
    --center c_cell \
    --grid_name ocean_vgrid || fail_ failed to create ocean vgrid
# Ensure ocean_vgrid.nc is created
test -f ocean_vgrid.nc || fail_ ocean_vgrid.nc not created
