#!/bin/sh

# Copyright (C) 2024 Geophysical Fluid Dynamics Laboratory

# This file is part of the GFDL FRE NetCDF tools package (FRE-NCTools).

# FRE-NCtools is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# FRE-NCtools is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.

# You should have received a copy of the GNU Lesser General Public
# License along with FRE-NCTools.  If not, see
# <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes
then
    set -x
fi

. "${srcdir=.}/init.sh"

# Create ocean hgrid
make_hgrid \
    --grid_type tripolar_grid \
    --nxbnd 2 \
    --nybnd 7 \
    --xbnd -280,80 \
    --ybnd -82,-30,-10,0,10,30,90 \
    --dlon 1.0,1.0 \
    --dlat 1.0,1.0,0.6666667,0.3333333,0.6666667,1.0,1.0 \
    --grid_name ocean_hgrid \
    --center c_cell || framework_failure_ failed to create ocean hgrid

# create ocean solo mosaic
make_solo_mosaic \
    --num_tiles 1 \
    --dir . \
    --mosaic_name ocean_mosaic \
    --tile_file ocean_hgrid.nc \
    --periodx 360 || fail_ failed to create ocean solo mosaic
# Ensure ocean_mosaic.nc is created
test -f ocean_mosaic.nc || fail_ ocean_mosaic.nc not created
