#!/bin/sh

# Copyright (C) 2024 Geophysical Fluid Dynamics Laboratory

# This file is part of the GFDL FRE NetCDF tools package (FRE-NCTools).

# FRE-NCtools is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# FRE-NCtools is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.

# You should have received a copy of the GNU Lesser General Public
# License along with FRE-NCTools.  If not, see
# <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes
then
    set -x
fi

. "${srcdir=.}/init.sh"

# Test grid for coupled model (land and atmosphere are C48 and ocean is 1 degree
# tripolar grid)

# Create ocean hgrid
make_hgrid \
	--grid_type tripolar_grid \
	--nxbnd 2 \
	--nybnd 7 \
	--xbnd -280,80 \
	--ybnd -82,-30,-10,0,10,30,90 \
	--dlon 1.0,1.0 \
	--dlat 1.0,1.0,0.6666667,0.3333333,0.6666667,1.0,1.0 \
	--grid_name ocean_hgrid \
	--center c_cell \
	|| framework_failure_ failed to create ocean hgrid

# create ocean_vgrid
make_vgrid \
	--nbnds 3 \
	--bnds 0.,220.,5500. \
	--dbnds 10.,10.,367.14286 \
    --center c_cell \
	--grid_name ocean_vgrid || framework_failure_ failed to create ocean vgrid

#create ocean solo mosaic
make_solo_mosaic  \
    --num_tiles 1  \
    --dir ./  \
    --mosaic_name ocean_mosaic  \
    --tile_file ocean_hgrid.nc  \
    --periodx 360 \
    || framework_failure_ failed to create ocean solo mosaic

$builddir/create_mask_topog || framework_failure_ Failed to create mask topography
check_mask \
    --grid_file ocean_mosaic.nc \
	--ocean_topog mask_topog.nc \
    --min_pe 100 \
	--max_pe 200 \
	--model ocean \
    || fail_ failed to create ocean mask files

expected_mask_files="mask_table.1.11x11
mask_table.1.13x11
mask_table.1.13x13
mask_table.1.13x9
mask_table.1.15x11
mask_table.1.15x13
mask_table.1.15x9
mask_table.1.17x11
mask_table.1.17x9
mask_table.1.7x15
mask_table.1.7x17
mask_table.1.7x19
mask_table.1.7x21
mask_table.1.9x19
mask_table.2.13x12
mask_table.2.14x11
mask_table.2.14x13
mask_table.2.14x9
mask_table.2.16x11
mask_table.2.16x9
mask_table.2.18x11
mask_table.2.9x18
mask_table.3.7x23
mask_table.3.7x25
mask_table.3.9x21"

ls -1 $expected_mask_files || fail_ one or more mask files are missing
