#!/bin/sh

# Copyright (C) 2024 Geophysical Fluid Dynamics Laboratory

# This file is part of the GFDL FRE NetCDF tools package (FRE-NCTools).

# FRE-NCtools is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# FRE-NCtools is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.

# You should have received a copy of the GNU Lesser General Public
# License along with FRE-NCTools.  If not, see
# <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes
then
    set -x
fi

. "${srcdir=.}/init.sh"


$builddir/create_ocean_mask_grid || framework_failure_ Failed to create mask grid
check_mask --grid_file ocean_mask_grid.nc \
    --min_pe 60 \
    --max_pe 80 \
    || fail_ failed to create ocean mask files

expected_mask_files="mask_table.1.7x11
mask_table.1.7x9"

ls -1 $expected_mask_files || fail_ one or more mask files are missing
