#!/bin/sh

# Copyright (C) 2024 Geophysical Fluid Dynamics Laboratory

# This file is part of the GFDL FRE NetCDF tools package (FRE-NCTools).

# FRE-NCtools is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# FRE-NCtools is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.

# You should have received a copy of the GNU Lesser General Public
# License along with FRE-NCTools.  If not, see
# <http://www.gnu.org/licenses/>.

# Get the base location of this script.  That is, the directory where the
# input files are also located

if test "$VERBOSE" = yes
then
    set -x
fi

. "${srcdir=.}/init.sh"

# create the grid_spec netCDF files from the text cdl files
$top_srcdir/tests/make_hgrid/create_fv3_grid_spec_files || framework_failure_ failed to create grid_spec files

# Use the grid_spec files to create the hgrid file
make_hgrid --grid_type from_file \
           --great_circle_algorithm \
           --my_grid $(ls grid_spec.tile*.nc | tr '\n' ',' | sed 's/,$//') \
           --grid_name C48_ff_grid \
           || fail_ to make hgrid files from grid_spec
# Ensure C48_ff_grid_tile1-].nc are created
for i in $(seq 1 6); do
    test -f C48_ff_grid.tile${i}.nc || failed_files="${failed_files} C48_ff_grid.tile${i}.nc"
done
if [ -n "${failed_files}" ]; then
    fail_ "failed to create ${failed_files}"
fi

# "Analytically" create a equal distance gnomonic cubic grid using the
# do_cube_transform option
make_hgrid \
    --grid_type gnomonic_ed \
    --nlon 96 \
    --do_cube_transform \
    --stretch_factor 3 \
    --target_lat 17.5 \
    --target_lon 172.5 \
    --grid_name C48_grid \
    || framework_failure_ failed to create C48 grid analytically

# comapre the two versions of grid files.  The from-file grid files were
# generated from the grid_spec files, so they should be the same as the
# analytically generated.  However, the grid_spec files are generated from
# a Fortran program, so there may be some small differences.
for i in $(seq 1 6); do
    $top_srcdir/tests/nc_cmp -d --variable=x,y,dx,dy --Tolerance=1.0e-9 \
        C48_ff_grid.tile${i}.nc C48_grid.tile${i}.nc \
        || fail_ "grid files differ for variables x, y, dx, dy: C48_ff_grid.tile${i}.nc C48_grid.tile${i}.nc"
    $top_srcdir/tests/nc_cmp -d --variable=area --Tolerance=1.0e-6 \
        C48_ff_grid.tile${i}.nc C48_grid.tile${i}.nc \
        || fail_ "grid files differ for variable area: C48_ff_grid.tile${i}.nc C48_grid.tile${i}.nc"
done