#!/bin/sh

# Copyright (C) 2024 Geophysical Fluid Dynamics Laboratory

# This file is part of the GFDL FRE NetCDF tools package (FRE-NCTools).

# FRE-NCtools is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# FRE-NCtools is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.

# You should have received a copy of the GNU Lesser General Public
# License along with FRE-NCTools.  If not, see
# <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes
then
    set -x
fi

. "${srcdir=.}/init.sh"

expensive_

# Test grid for coupled model (land and atmosphere are C48 and ocean is 1 degree
# tripolar grid)

# Create ocean hgrid
make_hgrid \
	--grid_type tripolar_grid \
	--nxbnd 2 \
	--nybnd 7 \
	--xbnd -280,80 \
	--ybnd -82,-30,-10,0,10,30,90 \
	--dlon 1.0,1.0 \
	--dlat 1.0,1.0,0.6666667,0.3333333,0.6666667,1.0,1.0 \
	--grid_name ocean_hgrid \
	--center c_cell || framework_failure_ failed to create ocean hgrid

# create ocean_vgrid
make_vgrid \
	--nbnds 3 \
	--bnds 0.,220.,5500. \
	--dbnds 10.,10.,367.14286 \
    --center c_cell \
	--grid_name ocean_vgrid || framework_failure_ failed to create ocean vgrid

# create ocean solo mosaic
make_solo_mosaic \
	--num_tiles 1 \
	--dir . \
	--mosaic_name ocean_mosaic \
	--tile_file ocean_hgrid.nc \
	--periodx 360 || framework_failure_ failed to create ocean solo mosaic

# create ocean topography data
$builddir/create_occam_topog || framework_failure_ failed to create OCCAM_p5degree.nc
make_topog \
	--mosaic ocean_mosaic.nc \
	--topog_type realistic \
	--topog_file OCCAM_p5degree.nc \
	--topog_field TOPO \
	--scale_factor -1 \
	--vgrid ocean_vgrid.nc \
	--output topog.nc || framework_failure_ failed to create ocean topography data

# create C48 grid for atmos/land
make_hgrid \
	--grid_type gnomonic_ed \
	--nlon 96 \
	--grid_name C48_grid || framework_failure_ failed to create C48 grid

# create C48 solo mosaic for atmos/land
make_solo_mosaic \
	--num_tiles 6 \
	--dir . \
	--mosaic C48_mosaic \
	--tile_file C48_grid.tile1.nc,C48_grid.tile2.nc,C48_grid.tile3.nc,C48_grid.tile4.nc,C48_grid.tile5.nc,C48_grid.tile6.nc \
    || framework_failure_ failed to create C48 solo mosaic

# create coupler_mosaic
make_coupler_mosaic \
	--atmos_mosaic C48_mosaic.nc \
	--ocean_mosaic ocean_mosaic.nc \
	--ocean_topog  topog.nc \
	--check \
	--area_ratio_thresh 1.e-10 \
	--mosaic_name grid_spec || fail_ failed to create coupler_mosaic
# Ensure grid_spec.nc is created
test -f grid_spec.nc || fail_ grid_spec.nc not created
