#!/bin/sh

#***********************************************************************
#                   GNU Lesser General Public License
#
# This file is part of the GFDL FRE NetCDF tools package (FRE-NCTools).
#
# FRE-NCTools is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# FRE-NCTools is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with FRE-NCTools.  If not, see
# <http://www.gnu.org/licenses/>.
#***********************************************************************

if test "$VERBOSE" = yes
then
    set -x
fi

. "${srcdir=.}/init.sh"

very_expensive_

#create ocean_hgrid
make_hgrid \
    --grid_type tripolar_grid \
    --nxbnd 2  \
    --nybnd 7  \
    --xbnd -280,80  \
    --ybnd -82,-30,-10,0,10,30,90 \
    --dlon 1.0,1.0  \
    --dlat 1.0,1.0,0.6666667,0.3333333,0.6666667,1.0,1.0 \
    --grid_name ocean_hgrid  \
    --center c_cell \
    || framework_failure_ failed to create ocean_hgrid

#create ocean_vgrid
make_vgrid \
    --nbnds 3  \
    --bnds 0.,220.,5500.  \
    --dbnds 10.,10.,367.14286  \
    --center c_cell  \
    --grid_name ocean_vgrid \
    || framework_failure_ failed to create ocean_vgrid

#create ocean solo mosaic
make_solo_mosaic  \
    --num_tiles 1  \
    --dir ./  \
    --mosaic_name ocean_mosaic  \
    --tile_file ocean_hgrid.nc  \
    --periodx 360 \
    || framework_failure_ failed to create ocean solo mosaic

#create ocean topography data
$builddir/create_5degree_topog \
    || framework_failure_ failed to create input file 5degree_topog.nc
make_topog  \
    --mosaic ocean_mosaic.nc  \
    --topog_type realistic  \
    --topog_file 5degree_topog.nc \
    --topog_field TOPO  \
    --scale_factor -1  \
    --vgrid ocean_vgrid.nc  \
    --output topog.nc \
    || framework_failure_ failed to create ocean topography data

#Create C48 grid with atmos nested grid.
make_hgrid  \
    --grid_type gnomonic_ed  \
    --nlon 96  \
    --grid_name atmos_grid  \
    --do_schmidt \
    --target_lat 48.15  \
    --target_lon -100.15  \
    --halo 3  \
    --stretch_factor 3 \
    --great_circle_algorithm  \
    --nest_grid  \
    --refine_ratio 3  \
    --parent_tile 4 \
    --istart_nest 21  \
    --iend_nest 60  \
    --jstart_nest 11  \
    --jend 70 \
    || framework_failure_ failed to create C48 grid

# create C48 solo mosaic for atmos
make_solo_mosaic  \
    --num_tiles 7  \
    --dir ./  \
    --mosaic atmos_mosaic  \
    --tile_file  atmos_grid.tile1.nc,atmos_grid.tile2.nc,atmos_grid.tile3.nc,atmos_grid.tile4.nc,atmos_grid.tile5.nc,atmos_grid.tile6.nc,atmos_grid.tile7.nc \
    || framework_failure_ failed to create C48 solo mosaic

#Create C144 grid for land
make_hgrid  \
    --grid_type gnomonic_ed  \
    --nlon 288  \
    --grid_name land_grid  \
    --do_schmidt \
    --target_lat 48.15  \
    --target_lon -100.15  \
    --halo 3  \
    --stretch_factor 3  \
    --great_circle_algorithm  \
    --nest_grid  \
    --refine_ratio 3  \
    --parent_tile 0 \
    || framework_failure_ failed to create land_grid

# create C144 solo mosaic for land
make_solo_mosaic  \
    --num_tiles 6  \
    --dir ./  \
    --mosaic land_mosaic \
    --tile_file land_grid.tile1.nc,land_grid.tile2.nc,land_grid.tile3.nc,land_grid.tile4.nc,land_grid.tile5.nc,land_grid.tile6.nc \
    || framework_failure_ failed to create C144 solo mosaic

# Use make_coupler_mosaic_parallel if compiled with MPI
if test "$MPIRUN" = ""
then
    make_coupler_mosaic \
        --atmos_mosaic atmos_mosaic.nc \
        --land_mosaic land_mosaic.nc \
        --ocean_mosaic ocean_mosaic.nc \
        --ocean_topog  topog.nc --interp_order 1 --mosaic_name grid_spec --check \
        || fail_ failed to create coupler_mosaic
else
    get_ncpu_
    $MPIRUN -n $ncpu make_coupler_mosaic_parallel \
        --atmos_mosaic atmos_mosaic.nc \
        --land_mosaic land_mosaic.nc --ocean_mosaic ocean_mosaic.nc \
        --ocean_topog  topog.nc --interp_order 1 --mosaic_name grid_spec --check \
        || fail_ failed to create coupler_mosaic
fi
test -f grid_spec.nc || fail_ grid_spec.nc not created

# Generate the reference grid_spec.nc file
ncgen -o grid_spec_ref.nc <<EOF
netcdf grid_spec {
dimensions:
    string = 255 ;
    nfile_aXo = 7 ;
    nfile_aXl = 14 ;
    nfile_lXo = 6 ;
variables:
    char atm_mosaic_dir(string) ;
        atm_mosaic_dir:standard_name = "directory_storing_atmosphere_mosaic" ;
    char atm_mosaic_file(string) ;
        atm_mosaic_file:standard_name = "atmosphere_mosaic_file_name" ;
    char atm_mosaic(string) ;
        atm_mosaic:standard_name = "atmosphere_mosaic_name" ;
    char lnd_mosaic_dir(string) ;
        lnd_mosaic_dir:standard_name = "directory_storing_land_mosaic" ;
    char lnd_mosaic_file(string) ;
        lnd_mosaic_file:standard_name = "land_mosaic_file_name" ;
    char lnd_mosaic(string) ;
        lnd_mosaic:standard_name = "land_mosaic_name" ;
    char ocn_mosaic_dir(string) ;
        ocn_mosaic_dir:standard_name = "directory_storing_ocean_mosaic" ;
    char ocn_mosaic_file(string) ;
        ocn_mosaic_file:standard_name = "ocean_mosaic_file_name" ;
    char ocn_mosaic(string) ;
        ocn_mosaic:standard_name = "ocean_mosaic_name" ;
    char ocn_topog_dir(string) ;
        ocn_topog_dir:standard_name = "directory_storing_ocean_topog" ;
    char ocn_topog_file(string) ;
        ocn_topog_file:standard_name = "ocean_topog_file_name" ;
    char aXo_file(nfile_aXo, string) ;
        aXo_file:standard_name = "atmXocn_exchange_grid_file" ;
    char aXl_file(nfile_aXl, string) ;
        aXl_file:standard_name = "atmXlnd_exchange_grid_file" ;
    char lXo_file(nfile_lXo, string) ;
        lXo_file:standard_name = "lndXocn_exchange_grid_file" ;

// global attributes:
        :grid_version = "0.2" ;
        :code_release_version = "2024.04" ;
        :great_circle_algorithm = "TRUE" ;
        :git_hash = "f68145bf0aaf91a39c65bc5e74422e5b482c8a90" ;
        :creationtime = "Tue Dec 10 17:32:49 2024" ;
        :hostname = "mlt-4743592.gfdl.noaa.gov" ;
        :history = "make_coupler_mosaic_parallel --atmos_mosaic atmos_mosaic.nc --land_mosaic land_mosaic.nc --ocean_mosaic ocean_mosaic.nc --ocean_topog topog.nc --interp_order 1 --mosaic_name grid_spec --check" ;
data:

 atm_mosaic_dir = "./" ;

 atm_mosaic_file = "atmos_mosaic.nc" ;

 atm_mosaic = "atmos_mosaic" ;

 lnd_mosaic_dir = "./" ;

 lnd_mosaic_file = "land_mosaic.nc" ;

 lnd_mosaic = "land_mosaic" ;

 ocn_mosaic_dir = "./" ;

 ocn_mosaic_file = "ocean_mosaic.nc" ;

 ocn_mosaic = "ocean_mosaic" ;

 ocn_topog_dir = "./" ;

 ocn_topog_file = "topog.nc" ;

 aXo_file =
  "atmos_mosaic_tile1Xocean_mosaic_tile1.nc",
  "atmos_mosaic_tile2Xocean_mosaic_tile1.nc",
  "atmos_mosaic_tile3Xocean_mosaic_tile1.nc",
  "atmos_mosaic_tile4Xocean_mosaic_tile1.nc",
  "atmos_mosaic_tile5Xocean_mosaic_tile1.nc",
  "atmos_mosaic_tile6Xocean_mosaic_tile1.nc",
  "atmos_mosaic_tile7Xocean_mosaic_tile1.nc" ;

 aXl_file =
  "atmos_mosaic_tile1Xland_mosaic_tile1.nc",
  "atmos_mosaic_tile1Xland_mosaic_tile6.nc",
  "atmos_mosaic_tile2Xland_mosaic_tile2.nc",
  "atmos_mosaic_tile3Xland_mosaic_tile1.nc",
  "atmos_mosaic_tile3Xland_mosaic_tile2.nc",
  "atmos_mosaic_tile3Xland_mosaic_tile3.nc",
  "atmos_mosaic_tile3Xland_mosaic_tile4.nc",
  "atmos_mosaic_tile3Xland_mosaic_tile5.nc",
  "atmos_mosaic_tile4Xland_mosaic_tile4.nc",
  "atmos_mosaic_tile4Xland_mosaic_tile6.nc",
  "atmos_mosaic_tile5Xland_mosaic_tile5.nc",
  "atmos_mosaic_tile5Xland_mosaic_tile6.nc",
  "atmos_mosaic_tile6Xland_mosaic_tile6.nc",
  "atmos_mosaic_tile7Xland_mosaic_tile4.nc" ;

 lXo_file =
  "land_mosaic_tile1Xocean_mosaic_tile1.nc",
  "land_mosaic_tile2Xocean_mosaic_tile1.nc",
  "land_mosaic_tile3Xocean_mosaic_tile1.nc",
  "land_mosaic_tile4Xocean_mosaic_tile1.nc",
  "land_mosaic_tile5Xocean_mosaic_tile1.nc",
  "land_mosaic_tile6Xocean_mosaic_tile1.nc" ;
}
EOF

$top_srcdir/tests/nc_cmp -dm grid_spec.nc grid_spec_ref.nc \
    || fail_ grid_spec.nc and grid_spec_ref.nc are different
