#!/bin/sh

# Copyright (C) 2024 Geophysical Fluid Dynamics Laboratory

# This file is part of the GFDL FRE NetCDF tools package (FRE-NCTools).

# FRE-NCtools is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# FRE-NCtools is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.

# You should have received a copy of the GNU Lesser General Public
# License along with FRE-NCTools.  If not, see
# <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes
then
    set -x
fi

. "${srcdir=.}/init.sh"

# Create ocean hgrid
make_hgrid \
    --grid_type tripolar_grid \
    --nxbnd 2 \
    --nybnd 7 \
    --xbnd -280,80 \
    --ybnd -82,-30,-10,0,10,30,90 \
    --dlon 1.0,1.0 \
    --dlat 1.0,1.0,0.6666667,0.3333333,0.6666667,1.0,1.0 \
    --grid_name ocean_hgrid \
    --center c_cell \
    || framework_failure_ failed to create ocean hgrid

# create ocean_vgrid
make_vgrid \
    --nbnds 3 \
    --bnds 0.,220.,5500. \
    --dbnds 10.,10.,367.14286 \
    --center c_cell \
    --grid_name ocean_vgrid || framework_failure_ failed to create ocean vgrid

# create ocean solo mosaic
make_solo_mosaic \
    --num_tiles 1 \
    --dir . \
    --mosaic_name ocean_mosaic \
    --tile_file ocean_hgrid.nc \
    --periodx 360 || framework_failure_ failed to create ocean solo mosaic

# create ocean topography data
$builddir/create_5degree_topog || framework_failure_ failed to create input file 5degree_topog.nc
make_topog \
    --mosaic ocean_mosaic.nc \
    --topog_type realistic \
    --topog_file 5degree_topog.nc \
    --topog_field TOPO \
    --scale_factor -1 \
    --vgrid ocean_vgrid.nc \
    --output topog.nc || framework_failure_ failed to create ocean topography data

#Make the quick mosaic
make_quick_mosaic \
    --input_mosaic ocean_mosaic.nc \
    --ocean_topog topog.nc \
    || fail_ failed to create quick mosaic
# Check that the output files are created
test -f atmos_mosaic_tile1Xland_mosaic_tile1.nc \
    || fail_ atmos_mosaic_tile1Xland_mosaic_tile1.nc not created
test -f atmos_mosaic_tile1Xocean_mosaic_tile1.nc \
    || fail_ atmos_mosaic_tile1Xocean_mosaic_tile1.nc not created
test -f land_mosaic_tile1Xocean_mosaic_tile1.nc \
    || fail_ land_mosaic_tile1Xocean_mosaic_tile1.nc not created
test -f mosaic.nc \
    || fail_ mosaic.nc not created
