#!/bin/sh

# Copyright (C) 2024 Geophysical Fluid Dynamics Laboratory

# This file is part of the GFDL FRE NetCDF tools package (FRE-NCTools).

# FRE-NCtools is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# FRE-NCtools is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.

# You should have received a copy of the GNU Lesser General Public
# License along with FRE-NCTools.  If not, see
# <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes
then
    set -x
    command -v ncexists
    ncexists --version
fi

. "${srcdir=.}/init.sh"

$top_srcdir/tests/ncexists/create-test-file.sh || framework_failure_ "Failed to create test file"

# Both are tests that should fail.
ncexists && fail_ ncexists should exit with an error code if -f is not specified || true
ncexists -f does-not-exist.nc && fail_ ncexists should exit with an error code if the file does not exist || true
