#!/bin/sh

# Copyright (C) 2024 Geophysical Fluid Dynamics Laboratory

# This file is part of the GFDL FRE NetCDF tools package (FRE-NCTools).

# FRE-NCtools is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# FRE-NCtools is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.

# You should have received a copy of the GNU Lesser General Public
# License along with FRE-NCTools.  If not, see
# <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes
then
    set -x
    command -v split_ncvars.pl --version
fi

. ${srcdir=.}/init.sh; path_prepend_ ../src

test $have_plmod_list_moreutils = no && skip_ "perl module List::MoreUtils not available"

# Use the test netCDF files from plevel
${builddir=.}/create_plevel_test_ncfile || framework_failure_ "failed to create test files"

# Run split_ncvars.pl
output=$(split_ncvars.pl -p -VVV test_input.nc) || fail_ split_ncvars.pl test_input.nc failed
# Check for expected output
grep -q 'var=temp; timename=time; vlist=temp,ps,pk,bk' <<< "$output" || fail_ output does not contain expected output
