#!/bin/sh

# Copyright (C) 2024 Geophysical Fluid Dynamics Laboratory

# This file is part of the GFDL FRE NetCDF tools package (FRE-NCTools).

# FRE-NCtools is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# FRE-NCtools is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.

# You should have received a copy of the GNU Lesser General Public
# License along with FRE-NCTools.  If not, see
# <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes
then
    set -x
    command -v split_ncvars.pl --version
fi

. ${srcdir=.}/init.sh; path_prepend_ ../../src

# Need to use the included list_ncvars.sh script.  Otherwise,
# split_ncvars will look for list_ncvars.sh in the installed bin
# directory.
export LIST_NCVARS=$(readlink -f ../../src/list_ncvars.sh)

# list_ncvars.sh needs to know where to find the built list_ncvars
# executable.
export PKGLIBEXECDIR=$(readlink -f ../../src)

# Use the test netCDF files from timeavg
${builddir=..}/create_timeavg_test_ncfiles || framework_failure_ "failed to create test files"

# Run split_ncvars.pl
split_ncvars.pl -l test_input_1.nc || fail_ split_ncvars.pl test_input.nc failed
# Check that the README file was created
test -f README || fail_ README not created

expected_output="           time_bnds = time axis boundaries (days)
                var1 = variable 1 (s)
                var2 =  ()"
test x"$(cat README)" = x"$expected_output" || fail_ README does not contain expected output
